### ISSUE TITLE
Simplify DB configuration

### ISSUE THREAD

**Issue by alexandrosfilios** [hyperledger-labs/fabric-token-sdk#953]
Currently, we have one DB configuration per topic, e.g. identity, metadata, tokens. Also, there is a "unity" type that re-uses one DB and all tables are under this DB.

Example

```
  kvs:
    persistence:
      type: sql
      opts:
        driver: postgres
        dataSource: host=localhost port=22001 user=pgx_md5 password=example dbname=banka-db sslmode=disable
        createSchema: false
        tablePrefix:     
        maxOpenConns: 200
        maxIdleConns: 3
        maxIdleTime: 45s
    cache:
        # Sets the maximum number of cached items 
        size: 200
  binding:
    persistence:
      type: sql
      opts:
        driver: postgres
        dataSource: host=localhost port=22001 user=pgx_md5 password=example dbname=banka-db sslmode=disable
        createSchema: false
        tablePrefix:     
        maxOpenConns: 200
        maxIdleConns: 3
        maxIdleTime: 45s
  signerinfo:
    persistence:
      type: sql
      opts:
        driver: postgres
        dataSource: host=localhost port=22001 user=pgx_md5 password=example dbname=banka-db sslmode=disable
        createSchema: false
        tablePrefix:     
        maxOpenConns: 200
        maxIdleConns: 3
        maxIdleTime: 45s
```

Adapt configuration so that by default all topics use the same DB unless specified otherwise (possibility to overrule).

Do not forget to adapt the core.yaml documentation.
